/* This file is automatically generated from the documentation. EDIT AT YOUR OWN RISK. */

#ifndef UVROOT_CLI_H
#define UVROOT_CLI_H

#include "cli/cli.h"

#ifndef VERSION
#define VERSION "5.4.1"
#endif

static const char *recommended_bindings[] = {
    "/etc/host.conf",
    "/etc/hosts",
    "/etc/hosts.equiv",
    "/etc/mtab",
    "/etc/netgroup",
    "/etc/networks",
    "/etc/passwd",
    "/etc/group",
    "/etc/nsswitch.conf",
    "/etc/resolv.conf",
    "/etc/localtime",
    "/dev/",
    "/sys/",
    "/proc/",
    "/tmp/",
    "/run/",
    "/var/run/dbus/system_bus_socket",
/*	"/var/tmp/kdecache-$LOGNAME", */
    "$HOME",
    "*path*",
    NULL,
};

static const char *recommended_su_bindings[] = {
    "/etc/host.conf",
    "/etc/hosts",
    "/etc/nsswitch.conf",
    "/etc/resolv.conf",
    "/dev/",
    "/sys/",
    "/proc/",
    "/tmp/",
    "/run/shm",
    "$HOME",
    "*path*",
    NULL,
};

static int handle_option_r(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_b(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_q(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_mixed_mode(Tracee * tracee, const Cli * cli,
				    const char *value);
static int handle_option_w(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_v(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_V(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_h(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_k(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_i(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_p(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_n(Tracee * tracee, const Cli * cli,
			   const char *value);
#ifdef HAVE_PYTHON_EXTENSION
static int handle_option_P(Tracee * tracee, const Cli * cli,
			   const char *value);
#endif
static int handle_option_l(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_R(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_S(Tracee * tracee, const Cli * cli,
			   const char *value);
static int handle_option_kill_on_exit(Tracee * tracee, const Cli * cli,
				      const char *value);
static int handle_option_netfs(Tracee * tracee, const Cli * cli,
			       const char *value);
static int handle_option_ftp(Tracee * tracee, const Cli * cli,
			     const char *value);
static int handle_option_smb(Tracee * tracee, const Cli * cli,
			     const char *value);
static int handle_option_nfs(Tracee * tracee, const Cli * cli,
			     const char *value);
static int handle_option_iscsi(Tracee * tracee, const Cli * cli,
			       const char *value);
static int handle_option_nbd(Tracee * tracee, const Cli * cli,
			     const char *value);
static int handle_option_img(Tracee * tracee, const Cli * cli,
			     const char *value);
static int handle_option_qcow2(Tracee * tracee, const Cli * cli,
			       const char *value);
static int handle_option_net(Tracee * tracee, const Cli * cli,
			     const char *value);
static int handle_option_net_if(Tracee * tracee, const Cli * cli,
				const char *value);
static int handle_option_net_route(Tracee * tracee, const Cli * cli,
				   const char *value);
static int handle_option_wg(Tracee * tracee, const Cli * cli,
			    const char *value);
static int handle_option_net_bridge(Tracee * tracee, const Cli * cli,
				    const char *value);
static int handle_option_vpid(Tracee * tracee, const Cli * cli,
			      const char *value);
static int handle_option_vperm(Tracee * tracee, const Cli * cli,
			       const char *value);
static int handle_option_vperm_file(Tracee * tracee, const Cli * cli,
				    const char *value);
static int handle_option_vperm_id(Tracee * tracee, const Cli * cli,
				  const char *value);
static int handle_option_read_only(Tracee * tracee, const Cli * cli,
				   const char *value);
static int handle_option_ro(Tracee * tracee, const Cli * cli,
			    const char *value);
static int handle_option_vperm_map(Tracee * tracee, const Cli * cli,
				   const char *value);
static int handle_option_vperm_nosu(Tracee * tracee, const Cli * cli,
				    const char *value);

static int pre_initialize_bindings(Tracee *, const Cli *, size_t,
				   char *const *, size_t);
static int post_initialize_exe(Tracee *, const Cli *, size_t,
			       char *const *, size_t);

static Cli uvroot_cli = {
    .version = VERSION,
    .name = "uvroot",
    .subtitle =
	"chroot, mount --bind, and binfmt_misc without privilege/setup",
    .synopsis = "uvroot [option] ... [command]",
    .colophon =
	"uvroot - a user-mode virtual root, forked from PRoot\n\
Upstream PRoot: https://github.com/proot-me/proot\n\
Copyright (C) 2026 uvroot Developers, licensed under GPL v2 or later.\n\
Based on PRoot, Copyright (C) 2015 STMicroelectronics.",
    .logo = "\
 _____ _____              ___\n\
|  __ \\  __ \\_____  _____|   |_\n\
|   __/     /  _  \\/  _  \\    _|\n\
|__|  |__|__\\_____/\\_____/\\____|",

    .pre_initialize_bindings = pre_initialize_bindings,
    .post_initialize_exe = post_initialize_exe,

    .options = {
		{.class = "Regular options",
		 .arguments = {
			       {.name = "-r",.separator = ' ',.value =
				"path"},
			       {.name = "--rootfs",.separator =
				'=',.value = "path"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_r,
		 .description =
		 "Use *path* as the new guest root file-system, default is /.",
		 .detail =
		 "\tThe specified path typically contains a Linux distribution where\n\
\tall new programs will be confined.  The default rootfs is /\n\
\twhen none is specified, this makes sense when the bind mechanism\n\
\tis used to relocate host files and directories, see the -b\n\
\toption and the Examples section for details.\n\
\t\n\
\tIt is recommended to use the -R or -S options instead.",
		 },
		{.class = "Regular options",
		 .arguments = {
			       {.name = "-b",.separator = ' ',.value =
				"path"},
			       {.name = "--bind",.separator =
				'=',.value = "path"},
			       {.name = "-m",.separator = ' ',.value =
				"path"},
			       {.name = "--mount",.separator =
				'=',.value = "path"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_b,
		 .description =
		 "Make the content of *path* accessible in the guest rootfs.",
		 .detail =
		 "\tThis option makes any file or directory of the host rootfs\n\
\taccessible in the confined environment just as if it were part of\n\
\tthe guest rootfs.  By default the host path is bound to the same\n\
\tpath in the guest rootfs but users can specify any other location\n\
\twith the syntax: -b *host_path*:*guest_location*.  If the\n\
\tguest location is a symbolic link, it is dereferenced to ensure\n\
\tthe new content is accessible through all the symbolic links that\n\
\tpoint to the overlaid content.  In most cases this default\n\
\tbehavior shouldn't be a problem, although it is possible to\n\
\texplicitly not dereference the guest location by appending it the\n\
\t! character: -b *host_path*:*guest_location!*.",
		 },
		{.class = "Regular options",
		 .arguments = {
			       {.name = "-q",.separator = ' ',.value =
				"command"},
			       {.name = "--qemu",.separator =
				'=',.value = "command"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_q,
		 .description =
		 "Execute guest programs through QEMU as specified by *command*.",
		 .detail =
		 "\tEach time a guest program is going to be executed, uvroot inserts\n\
\tthe QEMU user-mode command in front of the initial request.\n\
\tThat way, guest programs actually run on a virtual guest CPU\n\
\temulated by QEMU user-mode.  The native execution of host programs\n\
\tis still effective and the whole host rootfs is bound to\n\
\t/host-rootfs in the guest environment.",
		 },
		{.class = "Regular options",
		 .arguments = {
			       {.name = "--mixed-mode",.separator =
				' ',.value = "value"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_mixed_mode,
		 .description = "Disable the mixed-execution feature.",
		 .detail =
		 "\tDo not treat ELF executables specially when they appear to be\n\
\tnative executables of the host system.",
		 },
		{.class = "Regular options",
		 .arguments = {
			       {.name = "-w",.separator = ' ',.value =
				"path"},
			       {.name = "--pwd",.separator =
				'=',.value = "path"},
			       {.name = "--cwd",.separator =
				'=',.value = "path"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_w,
		 .description =
		 "Set the initial working directory to *path*.",
		 .detail =
		 "\tSome programs expect to be launched from a given directory but do\n\
\tnot perform any chdir by themselves.  This option avoids the\n\
\tneed for running a shell and then entering the directory manually.",
		 },
		{.class = "Regular options",
		 .arguments = {
			       {.name = "--kill-on-exit",.separator =
				'\0',.value = NULL},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_kill_on_exit,
		 .description = "Kill all processes on command exit.",
		 .detail =
		 "\tWhen the executed command leaves orphean or detached processes\n\
\taround, uvroot waits until all processes possibly terminate. This option forces\n\
\tthe immediate termination of all tracee processes when the main command exits.",
		 },
		{.class = "Regular options",
		 .arguments = {
			       {.name = "-v",.separator = ' ',.value =
				"value"},
			       {.name = "--verbose",.separator =
				'=',.value = "value"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_v,
		 .description =
		 "Set the level of debug information to *value*.",
		 .detail =
		 "\tThe higher the integer value is, the more detailed debug\n\
\tinformation is printed to the standard error stream.  A negative\n\
\tvalue makes uvroot quiet except on fatal errors.",
		 },
		{.class = "Regular options",
		 .arguments = {
			       {.name = "-V",.separator = '\0',.value =
				NULL},
			       {.name = "--version",.separator =
				'\0',.value = NULL},
			       {.name = "--about",.separator =
				'\0',.value = NULL},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_V,
		 .description =
		 "Print version, copyright, license and contact, then exit.",
		 .detail = "",
		 },
		{.class = "Regular options",
		 .arguments = {
			       {.name = "-h",.separator = '\0',.value =
				NULL},
			       {.name = "--help",.separator =
				'\0',.value = NULL},
			       {.name = "--usage",.separator =
				'\0',.value = NULL},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_h,
		 .description =
		 "Print the version and the command-line usage, then exit.",
		 .detail = "",
		 },
		{.class = "Extension options",
		 .arguments = {
			       {.name = "-k",.separator = ' ',.value =
				"string"},
			       {.name = "--kernel-release",.separator =
				'=',.value = "string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_k,
		 .description =
		 "Make current kernel appear as kernel release *string*.",
		 .detail =
		 "\tIf a program is run on a kernel older than the one expected by its\n\
\tGNU C library, the following error is reported: \"FATAL: kernel too\n\
\told\".  To be able to run such programs, uvroot can emulate some of\n\
\tthe features that are available in the kernel release specified by\n\
\t*string* but that are missing in the current kernel.",
		 },
		{.class = "Extension options",
		 .arguments = {
			       {.name = "-i",.separator = ' ',.value =
				"string"},
			       {.name = "--change-id",.separator =
				'=',.value = "string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_i,
		 .description =
		 "Make current user and group appear as *string* \"uid:gid\".",
		 .detail =
		 "\tThis option makes the current user and group appear as uid and\n\
\tgid.  Likewise, files actually owned by the current user and\n\
\tgroup appear as if they were owned by uid and gid instead.\n\
\tThis is the same as -i 0:0.",
		 },
		{.class = "Extension options",
		 .arguments = {
			       {.name = "-p",.separator = ' ',.value =
				"string"},
			       {.name = "--port",.separator =
				'=',.value = "string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_p,
		 .description =
		 "Map ports to others with the syntax as *string* \"port_in:port_out\".",
		 .detail =
		 "\tThis option makes uvroot intercept bind and connect system calls,\n\
\tand change the port they use. The port map is specified\n\
\twith the syntax: -b *port_in*:*port_out*. For example,\n\
\tan application that runs a MySQL server binding to 5432 wants\n\
\tto cohabit with other similar application, but doesn't have an\n\
\toption to change its port. uvroot can be used here to modify\n\
\tthis port: uvroot -p 5432:5433 myapplication. With this command,\n\
\tthe MySQL server will be bound to the port 5433.\n\
\tThis command can be repeated multiple times to map multiple ports.",
		 },
		{.class = "Extension options",
		 .arguments = {
			       {.name = "-n",.separator = '\0',.value =
				NULL},
			       {.name = "--netcoop",.separator =
				'\0',.value = NULL},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_n,
		 .description = "Enable the network cooperation mode.",
		 .detail =
		 "\tThis option makes uvroot intercept bind() system calls and\n\
\tchange the port they are binding to to 0. With this, the system will\n\
\tallocate an available port. Each time this is done, a new entry is added\n\
\tto the port mapping entries, so that corresponding connect() system calls\n\
\tuse the same resulting port. This network \"cooperation\" makes it possible\n\
\tto run multiple instances of a same program without worrying about the same ports\n\
\tbeing used twice.",
		 },
#ifdef HAVE_PYTHON_EXTENSION
		{.class = "Extension options",
		 .arguments = {
			       {.name = "-P",.separator = ' ',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_P,
		 .description =
		 "Allow to access tracee information from python (experimental).",
		 .detail =
		 "\tThis option allow to launch a python script as an extension (experimental).",
		 },
#endif
		{.class = "Extension options",
		 .arguments = {
			       {.name = "-l",.separator = '\0',.value =
				NULL},
			       {.name = "--link2symlink",.separator =
				'\0',.value = NULL},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_l,
		 .description = "Enable the link2symlink extension.",
		 .detail =
		 "\tThis extension causes uvroot to create a symlink when a hardlink\n\
\tshould be created. Some environments don't let the user create a hardlink, this\n\
\toption should be used to fix it.",
		 },
		{.class = "Network mount options",
		 .arguments = {
			       {.name = "--netfs",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_netfs,
		 .description =
		 "Mount a remote or image-backed resource, e.g. *guest:uri*.",
		 .detail =
		 "\tThis option makes the content of a remote (or image-backed)\n\
\tresource readable and writable in the guest as if it were a local\n\
\tdirectory.  The syntax is *guest_directory*:*uri*; when the guest\n\
\tdirectory is omitted the resource is mounted under /mnt.  The backend\n\
\tis selected from the URI scheme: ftp://, ftps:// (implicit TLS),\n\
\tftpes:// (explicit TLS) and sftp:// are handled by libcurl, smb:// and\n\
\tcifs:// by libsmbclient.  The following schemes are registered but\n\
\treserved for future work: nfs://, iscsi://, nbd://, img:// (raw image)\n\
\tand qcow2://.\n\
\t\n\
\tThe resource is mirrored on demand into a private cache directory that\n\
\tis automatically bound into the guest, so no privilege, kernel module\n\
\tor /dev/fuse access is needed; this also works on unrooted Android.\n\
\tFile contents are fetched when a file is opened for reading and pushed\n\
\tback when the last descriptor is closed; mkdir, rmdir, unlink and\n\
\trename are forwarded to the remote side.",
		 },
		{.class = "Network mount options",
		 .arguments = {
			       {.name = "--ftp",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_ftp,
		 .description =
		 "Mount a FTP, FTPS or SFTP share, e.g. *guest:uri*.",
		 .detail =
		 "\tAlias for --netfs restricted to the ftp://, ftps://,\n\
\tftpes:// and sftp:// schemes, e.g.\n\
\t--ftp=/mnt/pub:ftp://user:password@host/pub.",
		 },
		{.class = "Network mount options",
		 .arguments = {
			       {.name = "--smb",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_smb,
		 .description =
		 "Mount a SMB/CIFS share, e.g. *guest:uri*.",
		 .detail =
		 "\tAlias for --netfs restricted to the smb:// and cifs://\n\
\tschemes, e.g. --smb=/mnt/share:smb://user:password@server/share.",
		 },
		{.class = "Network mount options",
		 .arguments = {
			       {.name = "--nfs",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_nfs,
		 .description =
		 "Mount a NFS export (reserved, not implemented yet).",
		 .detail =
		 "\tRegistered for future work; the NFS client is not\n\
\timplemented yet and this option currently reports an error.",
		 },
		{.class = "Network mount options",
		 .arguments = {
			       {.name = "--iscsi",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_iscsi,
		 .description =
		 "Mount an iSCSI LUN (reserved, not implemented yet).",
		 .detail =
		 "\tRegistered for future work; the iSCSI initiator and the\n\
\tfilesystem driver that will interpret the LUN are not implemented yet.",
		 },
		{.class = "Network mount options",
		 .arguments = {
			       {.name = "--nbd",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_nbd,
		 .description =
		 "Mount a NBD export (reserved, not implemented yet).",
		 .detail =
		 "\tRegistered for future work; the NBD client and the\n\
\tfilesystem driver that will interpret the export are not implemented yet.",
		 },
		{.class = "Network mount options",
		 .arguments = {
			       {.name = "--img",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_img,
		 .description =
		 "Mount a raw disk image (reserved, not implemented yet).",
		 .detail =
		 "\tRegistered for future work; the raw image backend and the\n\
\tfilesystem driver that will interpret the image are not implemented yet.",
		 },
		{.class = "Network mount options",
		 .arguments = {
			       {.name = "--qcow2",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_qcow2,
		 .description =
		 "Mount a QCOW2 disk image (reserved, not implemented yet).",
		 .detail =
		 "\tRegistered for future work; the QCOW2 backend and the\n\
\tfilesystem driver that will interpret the image are not implemented yet.",
		 },
		{.class = "Virtual permission options",
		 .arguments = {
			       {.name = "--vperm-nosu",.separator = '\0',.value =
				NULL},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_vperm_nosu,
		 .description =
		 "Do not expose the virtual su/sudo programs.",
		 .detail =
		 "\tAlso enables the feature.  The virtual /etc/passwd is still\n\
\tprovided, but su and sudo are not injected, so the virtual identity\n\
\tcannot be changed from inside the container: it is then fixed by\n\
\t--vperm-id when the container is started.",
		 },
		{.class = "Container options",
		 .arguments = {
			       {.name = "--read-only",.separator = '\0',.value =
				NULL},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_read_only,
		 .description =
		 "Refuse every change on the mounted images, id0 included.",
		 .detail =
		 "\tThe netfs mounts (--img, --qcow2, --netfs, --ftp, ...) are\n\
\tmarked read-only.  The refusal is enforced where the change would be\n\
\tapplied, so the virtual root cannot write either: any write, mkdir,\n\
\tunlink or rename returns EROFS.\n",
		 },
		{.class = "Container options",
		 .arguments = {
			       {.name = "--ro",.separator = '=',.value =
				"path"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_ro,
		 .description =
		 "Make one mapping read-only (repeatable).",
		 .detail =
		 "\t*path* is the guest side of the mapping: the mount point of\n\
\t--img/--qcow2/--netfs/--ftp/--smb/--nfs, the guest side of a -b\n\
\tbinding, or / for the rootfs given by -r.  Only that mapping is\n\
\taffected, and every identity is refused there -- id0 included.\n\
\t/ dev, /proc, /sys and /run stay writable, so a shell can still use\n\
\t/dev/null.  Example: --img=/data:disk.img --ro=/data\n",
		 },
		{.class = "Virtual permission options",
		 .arguments = {
			       {.name = "--vperm-map",.separator = '=',.value =
				"path"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_vperm_map,
		 .description =
		 "Use *path* as the user mapping directory.",
		 .detail =
		 "\tAlso enables the feature.  The directory holds users.conf\n\
\t(*name*:*uid*:*gid*[:*shell*] lines, one per line) and the generated\n\
\tsu/sudo shims, which are bound into the container so that su and sudo\n\
\twork there with the virtual identities.  Defaults to\n\
\t$XDG_DATA_HOME/uvroot/vperm (or ~/.local/share/uvroot/vperm).",
		 },
		{.class = "Virtual permission options",
		 .arguments = {
			       {.name = "--vperm-file",.separator = '=',.value =
				"path"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_vperm_file,
		 .description =
		 "Store the virtual permission database at *path*.",
		 .detail =
		 "\tAlso enables the feature.  The path must be absolute.  It is\n\
\tmainly useful to keep the database outside a netfs root, where it\n\
\twould otherwise be mirrored to the server.  Without this option a\n\
\tlocal rootfs uses *root*/.uvroot-vperm, and a database left behind\n\
\tunder the pre-rename name .proot-vperm is taken over automatically.",
		 },
		{.class = "Virtual permission options",
		 .arguments = {
			       {.name = "--vperm-id",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_vperm_id,
		 .description =
		 "Use *string* \"uid:gid\" as the virtual identity.",
		 .detail =
		 "\tAlso enables the feature.  The identity is what permission\n\
\tchecks and newly created files use; it defaults to the real\n\
\tuid and gid of the uvroot process.",
		 },
		{.class = "Virtual permission options",
		 .arguments = {
			       {.name = "--vperm",.separator = '\0',.value =
				NULL},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_vperm,
		 .description =
		 "Enable persistent virtual ownership and permissions.",
		 .detail =
		 "\tA small text database records a virtual uid, gid and mode for\n\
\ta subset of the paths of the guest root.  Programs inside the guest\n\
\tsee those values through the stat() family, chmod() and chown() only\n\
\tupdate the database -- the host metadata is never modified -- and\n\
\topen(), access() and execve() are checked against the recorded mode.\n\
\tPaths without an entry keep the host's own metadata.  The database is\n\
\tloaded at startup (a damaged one is fatal) and kept in sync by\n\
\tcreation, unlink, rmdir and rename.  Removing a path keeps its entry,\n\
\tand recreating that path refreshes the entry: the recorded virtual\n\
\towner is kept and the permission bits come from the creation.  For a\n\
\tlocal rootfs it is stored as *root*/.uvroot-vperm; for a netfs root,\n\
\twhose cache is temporary, it is kept outside of it (see\n\
\t--vperm-file).",
		 },
		{.class = "Virtual network options",
		 .arguments = {
			       {.name = "--net-bridge",.separator =
				'=',.value = "string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_net_bridge,
		 .description =
		 "Select the WireGuard bridge implementation.",
		 .detail =
		 "\tThe argument is a comma-separated list.  The first item sets\n\
\tthe implementation:\n\
\t\n\
\t    *userspace*   a user-space WireGuard implementation (default)\n\
\t    *kernel*      the in-kernel WireGuard driver (needs CAP_NET_ADMIN)\n\
\t    *nat*         the user-mode NAT fallback only\n\
\t    *none*        no bridge at all\n\
\t\n\
\tThe optional ``lib=/path`` item names a shared library exporting\n\
\t``uvroot_wg_ops`` (preferred, see the manual), and ``exec=/path`` an\n\
\texternal user-space implementation (wireguard-go, boringtun, ...).\n\
\tUVROOT_NETVIRT_WG_LIB and UVROOT_NETVIRT_WG_EXEC are the environment\n\
\tequivalents.\n",
		 },
		{.class = "Virtual network options",
		 .arguments = {
			       {.name = "--net-route",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_net_route,
		 .description =
		 "Add a route to the virtual routing table.",
		 .detail =
		 "\tThe syntax is *destination[/prefix]* followed by optional\n\
\t``via GATEWAY``, ``dev INTERFACE``, ``metric N`` and ``table N``\n\
\tclauses, for instance:\n\
\t\n\
\t    --net-route='10.8.0.0/24 dev vtun'\n\
\t    --net-route='default via 10.177.0.1 dev veth0'\n",
		 },
		{.class = "Virtual network options",
		 .arguments = {
			       {.name = "--net-if",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_net_if,
		 .description =
		 "Declare or tune a virtual interface, e.g. *name,addr=...*.",
		 .detail =
		 "\tThe argument is a comma-separated list whose first item is\n\
\tthe interface name, followed by options:\n\
\t\n\
\t    *addr=CIDR*   assign an IPv4/IPv6 address\n\
\t    *mtu=N*       set the MTU\n\
\t    *mac=ADDR*    set the MAC address\n\
\t    *kind=NAME*   link kind (veth, tun, dummy, wireguard, ...)\n\
\t    *wg=CONFIG*   attach a WireGuard configuration\n\
\t    *up* / *down* bring the interface up or down\n\
\t\n\
\t--net already creates veth0 and vtun; this option overrides them or\n\
\tadds more devices.  Example: --net-if=wlan0,addr=192.168.1.2/24,up\n",
		 },
		{.class = "Virtual network options",
		 .arguments = {
			       {.name = "--net",.separator = '\0',.value =
				NULL},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_net,
		 .description =
		 "Enable the WireGuard-bridged virtual network.",
		 .detail =
		 "\tInstall a user-mode virtual network in the container: two\n\
\tmapped devices, *veth0* for ordinary network I/O and *vtun* for\n\
\ttailscale/intranet traffic, plus the loopback.  Nothing is created at\n\
\tthe kernel level, so no privilege, kernel module or /dev/net/tun is\n\
\tneeded; the container's `ip link`, `ip addr` and `ip route` operate on\n\
\tthe virtual devices, and getifaddrs(3) reports them.\n\
\t\n\
\tThe devices are bridged over WireGuard in user space: when a user-space\n\
\timplementation is available (see --net-bridge) it is driven through its\n\
\tUAPI socket, with a socketpair standing in for the TUN device; without\n\
\tone, traffic falls back to a user-mode NAT through the host stack.\n",
		 },
		{.class = "Virtual network options",
		 .arguments = {
			       {.name = "--wg",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_wg,
		 .description =
		 "Attach a WireGuard configuration to an interface.",
		 .detail =
		 "\tThe syntax is *interface*:*configuration*.  The configuration\n\
\tis either a wg(8)/wg-quick file body (``[Interface]``/``[Peer]``\n\
\tsections with PrivateKey, Address, PublicKey, Endpoint, AllowedIPs,\n\
\tPersistentKeepalive, ...), a ``conf=/path/to/wg0.conf`` reference, or\n\
\ta flat ``private_key=...;peer=...;allowed_ip=...`` string.  It is\n\
\thanded to the user-space WireGuard implementation selected by\n\
\t--net-bridge; UVROOT_NETVIRT_WG_CONF provides a default.\n",
		 },
		{.class = "Virtual process id options",
		 .arguments = {
			       {.name = "--vpid",.separator = '=',.value =
				"string"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_vpid,
		 .description =
		 "Set the container's virtual process ids.",
		 .detail =
		 "\tGive the first program of the container the virtual process\n\
\tid *N*; its children get the following ones.  /proc is presented from\n\
\tthe virtual point of view: /proc/<vpid> maps to the real process,\n\
\t/proc/<pid>/status and /proc/<pid>/stat report the virtual pid and\n\
\tparent, the /proc listings only show the container's own processes,\n\
\tand a host pid is not accessible at all.\n",
		 },
		{.class = "Alias options",
		 .arguments = {
			       {.name = "-R",.separator = ' ',.value =
				"path"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_R,
		 .description =
		 "Alias: -r *path* + a couple of recommended -b.",
		 .detail =
		 "\tPrograms isolated in *path*, a guest rootfs, might still need to\n\
\taccess information about the host system, as it is illustrated in\n\
\tthe Examples section of the manual.  These host information\n\
\tare typically: user/group definition, network setup, run-time\n\
\tinformation, users' files, ...  On all Linux distributions, they\n\
\tall lie in a couple of host files and directories that are\n\
\tautomatically bound by this option:\n\
\t\n\
\t    * /etc/host.conf\n\
\t    * /etc/hosts\n\
\t    * /etc/hosts.equiv\n\
\t    * /etc/mtab\n\
\t    * /etc/netgroup\n\
\t    * /etc/networks\n\
\t    * /etc/passwd\n\
\t    * /etc/group\n\
\t    * /etc/nsswitch.conf\n\
\t    * /etc/resolv.conf\n\
\t    * /etc/localtime\n\
\t    * /dev/\n\
\t    * /sys/\n\
\t    * /proc/\n\
\t    * /tmp/\n\
\t    * /run/\n\
\t    * /var/run/dbus/system_bus_socket\n\
\t    * $HOME",
		 },
		{.class = "Alias options",
		 .arguments = {
			       {.name = "-S",.separator = ' ',.value =
				"path"},
			       {.name = NULL,.separator = '\0',.value =
				NULL}},
		 .handler = handle_option_S,
		 .description =
		 "Alias: -r *path* (as the root id) + recommended -b.",
		 .detail =
		 "\tThis option is useful to safely create and install packages into\n\
\tthe guest rootfs.  It is similar to the -R option except it\n\
\tfakes the root identity and binds only the following minimal set\n\
\tof paths to avoid unexpected changes on host files:\n\
\t\n\
\t    * /etc/host.conf\n\
\t    * /etc/hosts\n\
\t    * /etc/nsswitch.conf\n\
\t    * /etc/resolv.conf\n\
\t    * /dev/\n\
\t    * /sys/\n\
\t    * /proc/\n\
\t    * /tmp/\n\
\t    * /run/shm\n\
\t    * $HOME",
		 },
		END_OF_OPTIONS,
		 },
};

#endif				/* UVROOT_CLI_H */
